import GlobalStyles from '@/components/GlobalStyles';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalStyles />
      <body>{children}</body>
    </html>
  );
}
